name: ICARE-CICD-PRO

on:
  push:
    branches:
      - main
  
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'tumerin'
          
      - name: build project
        run: mvn clean package